version: "3"
services:
  def-occlum-keyring:
    # Before changing version numbers, make sure your device is in Standby status, or not registered. Otherwise you will be punished.
    image: deepsafe/def-occlum-keyring:v1.0.0
    restart: always
    network_mode: "host"
    environment:
        RUST_LOG: info
    volumes:
        - ./configs:/configs
        - ./data:/root/occlum_instance/data
        - ./configs/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf
    devices:
        - /dev/sgx/enclave:/dev/sgx/enclave
        - /dev/sgx/provision:/dev/sgx/provision
    command: bash -c 'cp /configs/keyring.toml /root/occlum_instance; cd /root/occlum_instance; occlum print mrsigner; occlum print mrenclave; occlum run /bin/def-keyring run /host/keyring.toml'
